name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon=tray_icon.png --add-data "tray_icon.png;." ai_block_tray.py
        
    - name: Install WiX Toolset
      run: |
        $wixUrl = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip"
        Invoke-WebRequest -Uri $wixUrl -OutFile wix.zip
        Expand-Archive wix.zip -DestinationPath wix
        echo "$pwd\wix" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name: Prepare MSI Build
      run: |
        mkdir -p installer/build
        copy dist\* installer\build\
        copy installer\uninstall.bat installer\build\
        copy installer\license.rtf installer\build\
        
    - name: Build MSI
      run: |
        cd installer
        candle.exe config.wxs -ext WixUIExtension -arch x64 -dBindPath.dist=build -dBindPath.installer=. -out build/config.wixobj
        light.exe build/config.wixobj -ext WixUIExtension -out build/AI_Block_Setup.msi
        cd ..
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          installer/build/AI_Block_Setup.msi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 